// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactCta from '@/components/sections/contact/ContactCta';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
        <SectionErrorBoundary name="contact">
              <ContactCta
          tag="GET STARTED"
          text="Move the deal forward with every number in view. Speak with our team to see Fidaris in action."
          primaryButton={{
            text: "Request a Demo",
            href: "#",
          }}
          secondaryButton={{
            text: "Explore Platform",
            href: "#platform",
          }}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
