// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "covenants" section.

import React from 'react';
import FeaturesArrowCards from '@/components/sections/features/FeaturesArrowCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function CovenantsSection(): React.JSX.Element {
  return (
    <div id="covenants" data-section="covenants">
        <SectionErrorBoundary name="covenants">
              <FeaturesArrowCards
        tag="COVENANT TESTING"
        title="Adaptive Covenants"
        description="Covenants that evolve with the deal, not static spreadsheet checks."
        items={[{"tags":["Real-time"],"imageSrc":"https://images.unsplash.com/photo-1614850523459-c2f4c699c52e?q=80&w=2000&auto=format&fit=crop","title":"Threshold Monitoring"},{"title":"Forecast Positioning","imageSrc":"https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?q=80&w=2000&auto=format&fit=crop","tags":["Predictive"]},{"title":"Source Validation","tags":["Audit"],"imageSrc":"https://images.unsplash.com/photo-1633412802994-5c058f151b66?q=80&w=2000&auto=format&fit=crop"}]}
        textAnimation="fade-blur"
      />
        </SectionErrorBoundary>
      </div>
  );
}
