// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "covenants" section.

import React from 'react';
import FeaturesArrowCards from '@/components/sections/features/FeaturesArrowCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function CovenantsSection(): React.JSX.Element {
  return (
    <div id="covenants" data-section="covenants">
        <SectionErrorBoundary name="covenants">
              <FeaturesArrowCards
          tag="COVENANT TESTING"
          title="Adaptive Covenants"
          description="Covenants that evolve with the deal, not static spreadsheet checks."
          items={[
            {
              title: "Threshold Monitoring",
              tags: [
                "Real-time",
              ],
              imageSrc: "http://img.b2bpic.net/free-photo/male-administrator-using-chroma-key-display-digital-analysis_482257-126246.jpg",
            },
            {
              title: "Forecast Positioning",
              tags: [
                "Predictive",
              ],
              imageSrc: "http://img.b2bpic.net/free-photo/close-up-latest-financial-results-desk_1098-1983.jpg",
            },
            {
              title: "Source Validation",
              tags: [
                "Audit",
              ],
              imageSrc: "http://img.b2bpic.net/free-photo/teleworker-home-office-gathering-information-from-internet-seminar_482257-119301.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
