// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroSplitMediaGrid from '@/components/sections/hero/HeroSplitMediaGrid';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroSplitMediaGrid
        tag="FIDARIS DEVELOPMENT FINANCE"
        title="TRUST, UNDERWRITTEN."
        description="The live development-finance platform where developers, lenders, and every critical number meet. Build the deal once. Reconcile every source. Move from feasibility to credit decision with full visibility."
        primaryButton={{
            text: "Request a Demo",
            href: "#contact",
          }}
        secondaryButton={{
            text: "Explore the Platform",
            href: "#platform",
          }}
        items={[{"imageSrc":"https://images.unsplash.com/photo-1614850523459-c2f4c699c52e?q=80&w=2670&auto=format&fit=crop"},{"imageSrc":"https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?q=80&w=2000&auto=format&fit=crop"}]}
        textAnimation="fade-blur"
      />
        </SectionErrorBoundary>
      </div>
  );
}
