// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroSplitMediaGrid from '@/components/sections/hero/HeroSplitMediaGrid';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroSplitMediaGrid
          tag="FIDARIS DEVELOPMENT FINANCE"
          title="TRUST, UNDERWRITTEN."
          description="The live development-finance platform where developers, lenders, and every critical number meet. Build the deal once. Reconcile every source. Move from feasibility to credit decision with full visibility."
          primaryButton={{
            text: "Request a Demo",
            href: "#contact",
          }}
          secondaryButton={{
            text: "Explore the Platform",
            href: "#platform",
          }}
          items={[
            {
              imageSrc: "http://img.b2bpic.net/free-photo/patriot-day-commemoration-high-angle_52683-94469.jpg",
            },
            {
              imageSrc: "http://img.b2bpic.net/free-photo/future-visions-business-technology-concept_23-2151893436.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
