// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "intelligence" section.

import React from 'react';
import AboutTestimonial from '@/components/sections/about/AboutTestimonial';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function IntelligenceSection(): React.JSX.Element {
  return (
    <div id="intelligence" data-section="intelligence">
        <SectionErrorBoundary name="intelligence">
              <AboutTestimonial
          tag="INTELLIGENCE"
          quote="Specialist AI agents draft assessments across six disciplines. Every decision, however, remains visible, reviewable, and human-approved. Intelligence without losing control."
          author="Fidaris Engineering Team"
          role="Platform Governance"
          imageSrc="http://img.b2bpic.net/free-photo/woman-working-late-project_23-2149006067.jpg"
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
