// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "platform" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PlatformSection(): React.JSX.Element {
  return (
    <div id="platform" data-section="platform">
        <SectionErrorBoundary name="platform">
              <FeaturesImageBento
          tag="THE FIDARIS PLATFORM"
          title="ONE DEAL. ONE SOURCE OF TRUTH."
          description="High-fidelity interface design providing visibility across every critical deal component."
          items={[
            {
              title: "Deal Overview",
              description: "Unified project metrics.",
              imageSrc: "http://img.b2bpic.net/free-photo/determined-ceo-works-office-analyzing-infographics-setting-business-goals_482257-116818.jpg",
            },
            {
              title: "Covenant Status",
              description: "Continuous tracking.",
              imageSrc: "http://img.b2bpic.net/free-photo/notebook-economy-chart_23-2148542001.jpg",
            },
            {
              title: "Reconciliation",
              description: "Model vs Source data.",
              imageSrc: "http://img.b2bpic.net/free-photo/advisory-board-members-team-leaders-gathering-review-project-outcomes_482257-115651.jpg",
            },
            {
              title: "Assessment Flow",
              description: "AI-drafted reports.",
              imageSrc: "http://img.b2bpic.net/free-photo/advisory-board-members-meeting-boardroom-establish-future-development-plan_482257-113859.jpg",
            },
            {
              title: "Evidence Store",
              description: "Traceable documents.",
              imageSrc: "http://img.b2bpic.net/free-photo/closeup-african-american-entrepreneur-analyzing-company-profit_482257-20207.jpg",
            },
            {
              title: "Drawdown Progress",
              description: "Funding status.",
              imageSrc: "http://img.b2bpic.net/free-photo/computer-dark-room-with-graphs-screen_169016-57447.jpg",
            },
            {
              title: "Approval Gates",
              description: "Human controls.",
              imageSrc: "http://img.b2bpic.net/free-photo/forecast-expert-ceo-analyzing-investment-insights-negotiations-details_482257-116884.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
