// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "platform" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PlatformSection(): React.JSX.Element {
  return (
    <div id="platform" data-section="platform">
        <SectionErrorBoundary name="platform">
              <FeaturesImageBento
          tag="THE FIDARIS PLATFORM"
          title="ONE DEAL. ONE SOURCE OF TRUTH."
          description="High-fidelity interface design providing visibility across every critical deal component."
          items={[
            {
              title: <span className="text-white">Deal Overview</span>,
              description: <span className="text-white/90">Unified project metrics.</span>,
              imageSrc: "http://img.b2bpic.net/free-photo/joyful-businesswoman-holding-tablet_74855-2024.jpg",
            },
            {
              title: <span className="text-white">Covenant Status</span>,
              description: <span className="text-white/90">Continuous tracking.</span>,
              imageSrc: "http://img.b2bpic.net/free-photo/happy-executive-looking-information_1098-2091.jpg",
            },
            {
              title: <span className="text-white">Reconciliation</span>,
              description: <span className="text-white/90">Model vs Source data.</span>,
              imageSrc: "http://img.b2bpic.net/free-photo/cheerful-multiracial-business-team_1262-21007.jpg",
            },
            {
              title: <span className="text-white">Assessment Flow</span>,
              description: <span className="text-white/90">AI-drafted reports.</span>,
              imageSrc: "http://img.b2bpic.net/free-photo/smiling-corporate-businesswoman_23-2147702111.jpg",
            },
            {
              title: <span className="text-white">Evidence Store</span>,
              description: <span className="text-white/90">Traceable documents.</span>,
              imageSrc: "http://img.b2bpic.net/free-photo/smiling-businessmen-their-office_1098-81.jpg",
            },
            {
              title: <span className="text-white">Drawdown Progress</span>,
              description: <span className="text-white/90">Funding status.</span>,
              imageSrc: "http://img.b2bpic.net/free-photo/senior-businessman-with-arms-crossed-outside-modern-office-building_1139-1077.jpg",
            },
            {
              title: <span className="text-white">Approval Gates</span>,
              description: <span className="text-white/90">Human controls.</span>,
              imageSrc: "http://img.b2bpic.net/free-photo/elegant-business-woman-front-glass-building_23-2147704436.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
