// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "platform" section.

import React from 'react';
import FeaturesImageBento from '@/components/sections/features/FeaturesImageBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PlatformSection(): React.JSX.Element {
  return (
    <div id="platform" data-section="platform">
        <SectionErrorBoundary name="platform">
              <FeaturesImageBento
          tag="THE FIDARIS PLATFORM"
          title="ONE DEAL. ONE SOURCE OF TRUTH."
          description="High-fidelity interface design providing visibility across every critical deal component."
          items={[
            {
              title: "Deal Overview",
              description: "Unified project metrics.",
              imageSrc: "http://img.b2bpic.net/free-photo/joyful-businesswoman-holding-tablet_74855-2024.jpg",
            },
            {
              title: "Covenant Status",
              description: "Continuous tracking.",
              imageSrc: "http://img.b2bpic.net/free-photo/happy-executive-looking-information_1098-2091.jpg",
            },
            {
              title: "Reconciliation",
              description: "Model vs Source data.",
              imageSrc: "http://img.b2bpic.net/free-photo/cheerful-multiracial-business-team_1262-21007.jpg",
            },
            {
              title: "Assessment Flow",
              description: "AI-drafted reports.",
              imageSrc: "http://img.b2bpic.net/free-photo/smiling-corporate-businesswoman_23-2147702111.jpg",
            },
            {
              title: "Evidence Store",
              description: "Traceable documents.",
              imageSrc: "http://img.b2bpic.net/free-photo/smiling-businessmen-their-office_1098-81.jpg",
            },
            {
              title: "Drawdown Progress",
              description: "Funding status.",
              imageSrc: "http://img.b2bpic.net/free-photo/senior-businessman-with-arms-crossed-outside-modern-office-building_1139-1077.jpg",
            },
            {
              title: "Approval Gates",
              description: "Human controls.",
              imageSrc: "http://img.b2bpic.net/free-photo/elegant-business-woman-front-glass-building_23-2147704436.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}