```tsx
// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "reconciliation" section.

import React from 'react';
import MetricsSimpleCards from '@/components/sections/metrics/MetricsSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ReconciliationSection(): React.JSX.Element {
  return (
    <div id="reconciliation" data-section="reconciliation" className="py-24 bg-background">
        <SectionErrorBoundary name="reconciliation">
          <div className="w-content-width mx-auto">
            <div className="mb-16 text-center">
              <span className="text-accent font-semibold tracking-wider uppercase text-sm">RECONCILIATION</span>
              <h2 className="text-3xl md:text-4xl font-bold text-foreground mt-4 mb-4">Numbers That Agree</h2>
              <p className="text-lg text-foreground/70 max-w-2xl mx-auto">
                Identifying deviations between developer models, QS reports, and property valuations instantly.
              </p>
            </div>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
              {/* Card 1: Reconcile */}
              <div className="group perspective-1000 h-[400px]">