// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "reconciliation" section.

import React from 'react';
import MetricsSimpleCards from '@/components/sections/metrics/MetricsSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function ReconciliationSection(): React.JSX.Element {
  return (
    <div id="reconciliation" data-section="reconciliation">
        <SectionErrorBoundary name="reconciliation">
              <MetricsSimpleCards
          tag="RECONCILIATION"
          title="Numbers That Agree"
          description="Identifying deviations between developer models, QS reports, and property valuations instantly."
          metrics={[
            {
              value: "100%",
              description: "Traceability score",
            },
            {
              value: "Live",
              description: "QS comparison",
            },
            {
              value: "Verified",
              description: "Valuation check",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
