// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "security" section.

import React from 'react';
import MetricsSimpleCards from '@/components/sections/metrics/MetricsSimpleCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function SecuritySection(): React.JSX.Element {
  return (
    <div id="security" data-section="security">
        <SectionErrorBoundary name="security">
              <MetricsSimpleCards
          tag="SECURITY & TRUST"
          title="Designed for Decisions"
          description="Institutional-grade accountability for credit committees and property developers."
          metrics={[
            {
              value: "Controlled",
              description: "Access levels",
            },
            {
              value: "Visible",
              description: "Audit trails",
            },
            {
              value: "Accountable",
              description: "Human gates",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
