// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "storytelling" section.

import React from 'react';
import FeaturesArrowCards from '@/components/sections/features/FeaturesArrowCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function StorytellingSection(): React.JSX.Element {
  return (
    <div id="storytelling" data-section="storytelling">
        <SectionErrorBoundary name="storytelling">
              <FeaturesArrowCards
          tag="THE DEAL LIFECYCLE"
          title="Controlled, Accountable, Live."
          description="Progressively reconciled data moving from initial feasibility to final credit approval in a single controlled environment."
          items={[
            {
              title: "Build: One model starts the deal.",
              tags: [
                "Feasibility",
                "Modeling",
              ],
              imageSrc: "http://img.b2bpic.net/free-photo/still-life-graphics-arrangement_23-2148991185.jpg",
            },
            {
              title: "Reconcile: Figures brought to agreement.",
              tags: [
                "QS",
                "Valuation",
              ],
              imageSrc: "http://img.b2bpic.net/free-photo/futuristic-time-machine_23-2151599406.jpg",
            },
            {
              title: "Test: Live covenant verification.",
              tags: [
                "Covenants",
                "Funding",
              ],
              imageSrc: "http://img.b2bpic.net/free-photo/futuristic-time-machine_23-2151599423.jpg",
            },
            {
              title: "Assess: Specialist AI, human decision.",
              tags: [
                "AI Agents",
                "Approval",
              ],
              imageSrc: "http://img.b2bpic.net/free-photo/glowing-digital-sphere-futuristic-environment_23-2152020906.jpg",
            },
            {
              title: "Approve: Credit decision achieved.",
              tags: [
                "Credit",
                "Audit",
              ],
              imageSrc: "http://img.b2bpic.net/free-photo/3d-abstract-background-with-landscape-blocks_1048-12498.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
